/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BlueprintImport } from './routes/blueprint'
import { Route as IndustrialImport } from './routes/industrial'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlueprintRoute = BlueprintImport.update({
  path: '/6',
  getParentRoute: () => rootRoute,
} as any)

const IndustrialRoute = IndustrialImport.update({
  path: '/1',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/1': {
      id: '/1'
      path: '/1'
      fullPath: '/1'
      preLoaderRoute: typeof IndustrialImport
      parentRoute: typeof rootRoute
    }
    '/6': {
      id: '/6'
      path: '/6'
      fullPath: '/6'
      preLoaderRoute: typeof BlueprintImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  IndustrialRoute,
  BlueprintRoute,
})

/* prettier-ignore-end */
